export const __ASYNC_LOAD_ALL_ZHENTI_TONGJI = {
  pending: "ZhentiTongji/__LOAD_ALL_ZHENTI_TONGJI_PENDING",
  resolved: "ZhentiTongji/__LOAD_ALL_ZHENTI_TONGJI_RESOLVED",
  rejected: "ZhentiTongji/__LOAD_ALL_ZHENTI_TONGJI_REJECTED"
};

export const __ASYNC_LOAD_RECOMMAND_KNOWLEDGE_NAME = {
  pending: "TuijianZhishidian/__ASYNC_LOAD_RECOMMAND_KNOWLEDGE_NAME_PENDING",
  resolved: "TuijianZhishidian/__ASYNC_LOAD_RECOMMAND_KNOWLEDGE_NAME_RESOLVED",
  rejected: "TuijianZhishidian/__ASYNC_LOAD_RECOMMAND_KNOWLEDGE_NAME_REJECTED"
};

export const __ASYNC_LOAD_RECOMMAND_KNOWLEDGE_CONTENT = {
  pending: "TuijianZhishidianContent/__ASYNC_LOAD_RECOMMAND_KNOWLEDGE_CONTENT_PENDING",
  resolved: "TuijianZhishidianContent/__ASYNC_LOAD_RECOMMAND_KNOWLEDGE_CONTENT_RESOLVED",
  rejected: "TuijianZhishidianContent/__ASYNC_LOAD_RECOMMAND_KNOWLEDGE_CONTENT_REJECTED"
};

export const __ASYNC_LOAD_RECOMMAND_ARTICLE = {
  pending: "TuijianArticle/__ASYNC_LOAD_RECOMMAND_ARTICLE_PENDING",
  resolved: "TuijianArticle/__ASYNC_LOAD_RECOMMAND_ARTICLE_RESOLVED",
  rejected: "TuijianArticle/__ASYNC_LOAD_RECOMMAND_ARTICLE_REJECTED"
};
