export const __SET_LEARNING_TYPE = "LEARNING_TYPE/__SET_LEARNING_TYPE";
export const __ASYNC_LOAD_CHAPTER_NAME = {
  pending: "CHAPTERNAME/__LOAD_CHAPTER_NAME_PENDING",
  resolved: "CHAPTERNAME/__LOAD_CHAPTER_NAME_RESOLVED",
  rejected: "CHAPTERNAME/__LOAD_CHAPTER_NAME_REJECTED"
};
