export const __SAVE_OR_SUMBIT_TEXT = {
  pending: "EDIT_TEXT/__SAVE_OR_SUMBIT_TEXT_PENDING",
  resolved: "EDIT_TEXT/__SAVE_OR_SUMBIT_TEXT_RESOVLED",
  rejected: "EDIT_TEXT/__SAVE_OR_SUMBIT_TEXT_REJECTED",
};
export const __LOAD_LAST_SAVE_TEXT = {
  pending: "EDIT_TEXT/__LOAD_LAST_SAVE_TEXT_PENDING",
  resolved: "EDIT_TEXT/__LOAD_LAST_SAVE_TEXT_RESOVLED",
  rejected: "EDIT_TEXT/__LOAD_LAST_SAVE_TEXT_REJECTED",
};
export const __LOAD_ALL_SUBMIT_TEXT = {
  pending: "EDIT_TEXT/__LOAD_ALL_SUBMIT_TEXT_PENDING",
  resolved: "EDIT_TEXT/__LOAD_ALL_SUBMIT_TEXT_RESOVLED",
  rejected: "EDIT_TEXT/__LOAD_ALL_SUBMIT_TEXT_REJECTED",
};
